### ISSUE TITLE
Sending mail to google don't work

### ISSUE THREAD

**Issue by ghost** [noteed/docker-postfix#1]
It is not possible to send mails to for instance google accounts with this image.

I've added that postfix should use a smarthost to fix this, see
https://github.com/colmsjo/docker/tree/master/containers

**Comment by noteed** [comment]
Hi, it seems your use case is from within a virtual machine. When running directly from a VPS with a reverse DNS entry set up, I can send mails to gmail. Maybe an update to the documentation would be good though.
